plugins {
    id 'asphodel-loader'
    id 'fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${project.property('mc_1_20_1')}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${project.property('parchment_mc_1_20_1')}:${project.property('parchment_ver_1_20_1')}@zip")
    }
}

loom {
    mixin {
        defaultRefmapName.set("${project.mod_id}.refmap.json")
    }
}